services:
  - type: web
    name: football-api
    env: java
    plan: free
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/*.jar
    branch: main
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
